apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bs-juice-shop-2
  annotations:
    github.com/project-slug: mend-scalac/bs-juice-shop-2
spec:
  type: other
  lifecycle: unknown
  owner: agatascalac
